version: "3"
services:
  minetest:
    image: lscr.io/linuxserver/minetest:latest
    container_name: minetest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CLI_ARGS=--gameid devtest --port 30000
    volumes:
      - /home/osboxes/Docker/Minetest/.files-minetest:/config/.minetest
    ports:
      - 30000:30000/udp
    restart: unless-stopped
