version: "3"
services:
  db:
    image: mysql:5.7
    container_name: wordpressdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: letmein
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "666:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: letmein
      WORDPRESS_DB_NAME: db
    volumes: ["./:/var/www/html"]
volumes:
  mysql:
